### ISSUE TITLE
body_add_vg is defunct

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/SkeletonPredictionStudy#3]
I receive the error that `body_add_vg` from the rvg package is defunct and the suggestion is to use `officer::body_add_img` instead. `body_add_vg` is currently used in `CreatePlpProtocol.R`.

<img width="536" alt="Screenshot 2020-07-09 at 13 08 57" src="https://user-images.githubusercontent.com/7384198/87032766-62f33900-c1e5-11ea-8450-a53c290f7ebe.png">

Edit: Also received another error now, so there may also be a problem with my environment. I will follow up..

<img width="898" alt="Screenshot 2020-07-09 at 13 15 33" src="https://user-images.githubusercontent.com/7384198/87033324-515e6100-c1e6-11ea-9a11-cb9ee4916d05.png">

**Comment by jreps** [comment]
Hi Henrik, Thanks for letting me know about this.  I've updated the code using the suggested 'body_add_img' in the develop branch - are you able to test the new function with the results you have?

The second error was saying the input protocolLocation was invalid I think.
